# Generated by Django 3.2.10 on 2021-12-10 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportapp', '0002_auto_20211209_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
