# Generated by Django 3.2.10 on 2022-01-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportapp', '0003_customuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(default='profile_images/user.png', null=True, upload_to='profile_images/'),
        ),
    ]
