# Generated by Django 3.2.10 on 2022-01-22 14:40

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sportapp', '0004_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='follower',
            field=models.ManyToManyField(related_name='follower2', to=settings.AUTH_USER_MODEL),
        ),
    ]
