# Generated by Django 3.2.10 on 2022-01-22 16:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportapp', '0005_auto_20220122_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendshiprequest',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='friendshiprequest',
            name='to_user',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='is_public',
            new_name='equipment_needed',
        ),
        migrations.AddField(
            model_name='activity',
            name='max_players',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='activity',
            name='min_players',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='follower',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
        migrations.DeleteModel(
            name='FriendshipRequest',
        ),
    ]
