# Generated by Django 3.2.10 on 2022-01-25 09:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportapp', '0006_auto_20220122_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1024)),
                ('to_user', models.IntegerField(null=True)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 1, 25, 10, 15, 15, 408021))),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sportapp.activity')),
                ('from_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
